### ISSUE TITLE
Renaming the Brand - Ideas and thoughts

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#17]
When we started the brand of SQL Saturday, the idea was to not intrude on business days and ensure the event was open to all, as most organizations do not require work on Saturdays, There have been events on most days of the week, though some people have found an issue with the name.

1. Should we rename the brand to not link this to Saturday.
2. Suggestions?

 - Data Days
 - Data Inspiration
 - ??

**Comment by HugoKornelis** [comment]
Isn't this a duplicate of #11?

**Comment by tameraclark** [comment]
Branding is expensive. New signs will not be affordable for many events.

**Comment by way0utwest** [comment]
I bought [dataplatformdays.org](dataplatformdays.org) for these reasons
- the data platform is more than SQL, and more than MS
- avoiding trademark issues with xxSaturday
- community org, not really owned by anyone

That being said, I'm open to anything. I do think a brand matters, and while I hate to ask people to spend $$$ on new signs, shirts, etc., I am not hopeful that SQL Saturday can be purchased and kept going by 1 Feb 2021. If it cannot, then events may as well start moving to something new. Hence, I opened this issue.

**Comment by way0utwest** [comment]
It may be possible to get some support from a vendor or offer a sponsorship for signs, so the cost might not be a big issue. I suspect some generosity on this point from vendors.

**Comment by SQLClause** [comment]
Data Days is a name we've been discussing in Norway as both an option for opening up more on the weekday the event is held, as well as opening up for those who want to branch out a bit more. I fully agree that a lot of us branch out into more than just MS and more than just SQL these days, and this is more sensible. As for signs and stickers and other branding, as long as we're not enforcing branding like PASS tried to, does it really matter?

**Comment by way0utwest** [comment]
I honestly think that if this site is DataSaturday, but event 1045 is a redirect to DataDays.org in Norway, that's fine. I think multiple brands for an event can help it grow, and help different audiences find it. SQL Sat Cambridge was combined with SharepointSat Cambridge, and they jointly managed a schedule and marketed separately.

I think doing the same here is great.

**Comment by Dbakevlar** [comment]
Using SQL in the name closes many of the options to bring in new technology, in speakers, attendees and sponsors.  I like the idea of focusing the branding on data instead of SQL.

**Comment by steverezhener** [comment]
I slightly disagree with Kellyn. Most attendees, sponsors, speakers recognize that SQL in a SQL Saturday is just part of the brand. As an example, our SQLSatLA event had sessions on NoSQL, sharepoint, and excel. SQLSatLA event is not the only event with not SQL related sessions. That being said, if SQL Saturday brand could not be regained, Data is the way to go. BTW, http://datasaturday.com is owned by C&C.

**Comment by SQLClause** [comment]
Most *regular* attendees, sponsors and speakers recognize SQLSaturday is a brand. But branching out to new tech, sponsors and audiences who don't recognize the SQLSaturday brand is just as important. The regulars will understand, and the new ones will get onboard easier if we're not limiting to SQL

**Comment by datahai** [comment]
I’ll make a suggestion of Data Community Days (datacommunitydays.com and .org)

**Comment by way0utwest** [comment]
I think the shortlist of ideas is:
- Use xxx saturday.com (or multiple domains pointing to the same place) as a recognized brand
-  use something else that is more inclusive. 

Likely we need to come up with some voting mechanisms. Datacommunitydays.org and com are taken.

**Comment by datahai** [comment]
I registered the datacommunitydays domains. Happy to have over after any voting.

**Comment by transmokopter** [comment]
My five cents: Sql Saturday is likely not an option. If it is sold to commercial actor we don’t want a name that is too close. I thought of sqlfamily with sub domain for events. But that domain was registered 3 days ago it seems. By Contact Privacy Inc in Canada.

**Comment by way0utwest** [comment]
dataplatformdays.org is off the table. The Data Platform Geeks use this for free events, so I will be gifting them the domain.

I do like datacommunitydays as a general, not RDBMS focused name

**Comment by amtwo** [comment]
I'm in strong favor of dropping "Saturday" from the branding. 

* It creates brand confusion when xxxSaturday events are held on Friday for cultural/scheduling reasons.
* For locations & communities where Saturday is Sabbat or otherwise an impossible/impractical day of the week, it will create a distinct sense of _otherness_ for organizers & attendees. 
* There is already a history of international SQLSaturday events needing to be held on a different day, and this is our chance to "fix" the othering.
* DataSaturday.com is owned by C&C according to domain registration info. If they choose to launch or include this domain in the SQLSaturday sale, it may lead to brand confusion or copyright issues.

Some variation on "Data Day" gives the alliterative vibe which can be the hat tip to the alliterative SQL Saturday, while also being more inclusive.

## Brainstorming
* The plain "Data Day" is already in use by the broader Data community
* "Data Platform Day" or "Data Platform Days" is already used by the Data Platform Geeks

* "Data Community Day" or "Data Community Days" is available and @datahai owns the DataCommunityDays.com domain
* Look for available domains & brands that use "Day----" or "----day" compound words.
    * DataDaylight (.com is taken but unused. Other TLDs available)
    * DataEveryday  (.com is taken but unused. Other TLDs available)
    * DataMayday  (.com is taken but unused. Other TLDs available)
* Look for available domains & brands that use data puns, or data keywords. 
    * Datapoint Conference (DataPointConf.com & other domains available
    * Table Value conference (a bad pun on the value of data, and TVFs)
* Consider `.global`, `.pro`, `.tech`, `.community`, `.training` TLDs in addition to a traditional `.org` or `.com`

**Comment by way0utwest** [comment]
Added a discussion for this - https://github.com/sqlcollaborative/DataSaturdays/discussions/113

Closing this as it isn't an issue
