### ISSUE TITLE
Speaker Sessions CFP Platform

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#18]
Should we 
- build a platform that allows speaker submissions (and re-submissions to other events)
- use an existing platform like [https://sessionize.com/](Sessionize)
- both (build + integrate)

**Comment by bweissman** [comment]
I would at least start with integrating sessionize - while it may not check all the boxes, it does most of them

**Comment by HugoKornelis** [comment]
As a speaker, I love Sessionize for the simple reason that it allows me to submit abstracts without having to copy/paste the same information over and over.
The last years, SQLSaturdays had this option too, but from their own history of events. And, frankly, with a slightly sub-par interface.

The benefit of using Sessionize is that this would enable me to reuse session abstracts across *almost* all events I submit to.

**Comment by dhmacher** [comment]
Adding my two cents: we could create a unified email list (or similar mechanism) for speakers to subscribe to CFP announcements. Speakers could add tags for which technologies/platforms they know, as well as locations they are willing to speak at. Marcin Gminsky, @marcingminski, already has a data community calendar at https://datacommunity.events/events/.

**Comment by marcingminski** [comment]
Since I have been mentioned, I will ad my thoughts as I faced the same questions when building my aggregator. 

* build a platform that allows speaker submissions (and re-submissions to other events)
* use an existing platform like https://sessionize.com/
* both (build + integrate)

After talking to speakers, it became apparent that they like sessionize because it's platform agnostic, i.e. they can easily re-use the same event for different conferences and they would not want to re-type, copy-paste the same data into different websites hence I settled on automatically integrating what's already there with my calendar.

What I was also looking into is to integrate the speaker profiles so events and conferences can be filtered by a particular speaker but never had enough time to do much with it.

**Comment by way0utwest** [comment]
https://datasaturdays.com/

**Comment by SQLClause** [comment]
Sessionize is free for free events. If an event charges a lunch fee - is it free anymore from a Sessionize point of view?
I know pre-cons are a no-no, so you can't do pre-con CFP's without paying.
We might have to consider looking into the paid version of Sessionize?

But yeah, I do love the ease of use and platform agnostic approach of Sessionize.

**Comment by SQLDBAWithABeard** [comment]
I absolutely will say that we should use Sessionize, it makes it simple to use, it can feed a website simply and easily and it will be easy for us to code

**Comment by HugoKornelis** [comment]
In the early days of SQL Saturday when their interface didn't support pre-cons yet, calls for pre-cons were often handled in different ways. Eg. by just asking speakers to mail the organization.
Could that be used to enable free Sessionize usage? Or is that skimming the rules too much?

Are the sessionize rates high enough that we should worry?

**Comment by marcoparenzan** [comment]
My contribution: use sessionize.com. Don't reinvent the wheel.

**Comment by transmokopter** [comment]
I looked up the new features on sessionize. An important note if we go for integrating with sessionize is to include in t&c that the privacy option for the event in sessionize is open so speakers that don’t get notified can find the event. We can make sure using the sessionize api.

**Comment by suxstellino** [comment]
My two cents. Keep it simple and use just sessionize:
- it works
- it works very well
- it's comfortable
- it's been designed for speakers as well as organizers

Please don't reinvent the wheel. We will get all the stuff we need in a platform.

**Comment by SQLDBAWithABeard** [comment]
sessionize added via #149
