### ISSUE TITLE
Legal Entity for Assets

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#55]
While I do like this being a community effort and open source project, I do think that the long term sustainability and continuity likely requires some sort of legal entity that can own assets, handle money, and provide liability shielding for contributors.

I would propose a non-profit entity that does this, with the ability to hold funds used for various purposes, such as infrastructure. This would also allow Azure, AWS, etc,, to donate resources for hosting, email, etc.

The US has relatively few rules on a 501(3)(c) non proft - [https://en.wikipedia.org/wiki/501(c)(3)_organization](https://en.wikipedia.org/wiki/501(c)(3)_organization), though the US is also more litigious. 

I would also note that the US, with much of the vendors and sponsors located there, is perhaps easier to deal with for transferring funds.

Debate welcome.

My initial view would be that a board of directors (5-7) be elected somehow and hold 2-4 annual meetings for the purposes of strategic review of the group. I would also propose a group of 7-9 separate individuals act as a steering committee for ongoing operations. Each group would work for a term of 1-2 years.

**Comment by amtwo** [comment]
If there is a legal entity, I think it _must_ be a proper 501(c)(3) or 501(c)(6) tax exempt organization. 

A 501(c)(3) includes organizations with educational missions. The main criteria to qualify would be for the primary purpose, and majority of spending be spent on educational programs. The theoretical organization would likely qualify for this, but we'd want to check with a tax attorney.

A 501(c)(6) is a business league -- like your local Chamber of Commerce, or Trade group. The NFL is a 501(c)(6). If the organization didn't qualify as a (c)(3), it would surely qualify as a (c)(6). 

The main difference is around tax deductions for payments _to_ the organization. Donations to a (c)(3) are pretty much always eligible as a tax-deductible donation, but payments to a (c)(6) are not deductible as donations--I believe they count as business expenses.


### All that said... Is it a good idea? 
**Probably**. I think it's dangerous for the stability of the community to have assets held by individuals. SQLBlog.com fell apart in part because a single individual held the domain & managed hosting...and those haven't been maintained. 

### When should it be formed?
I don't think we need to have it set up on Day 1--but I think when the project reaches "critical mass" we will need to take this step. By then, experience will also help clarify questions around qualifying for (c)(3) status, involved individuals, etc.

### What should it look like?
I have no idea. 

I think the "Board elected **by the membership**" concept of PASS was a failure. Despite the bureaucracy of the NomCom, elections were less about voting on the issues or qualified candidates, and were heavily just a popularity contest. This did not consistently produce a diverse Board of Directors, nor a Board that was skilled in the areas of need.

I think the Board should be selected by the Board itself, similar to [The Mozilla Foundation](https://wiki.mozilla.org/Board/FAQ#How_are_board_members_chosen.3F). The Board would then select the Steering Committee members. I would like to see decisions on structure based on research of how other successful non-profits (Tech/open-source, and otherwise) select their leadership. 

There should be a dedicated role as part of Board member or Steering Committee member(s) that is dedicated to Diversity, Inclusion, Culture, and Belonging--- a "Culture & Inclusion Chair" or something. In fact--this should probably happen even without a legal entity, but particularly with one. Having Inclusion run _throughout_ every aspect of any organization or project is going to be critical to success. It is a constant problem in Tech, and requires enough effort, research, knowledge, and experience that having it "assigned" to someone to help lead efforts.

**Comment by way0utwest** [comment]
Good thoughts. I've been hesitant to have self-selected individuals have too much of a say, but maybe that's not a bad choice. 

I need to do this for T-SQL Tuesday as well, either in a legal entity here or another one.

**Comment by amtwo** [comment]
I wouldn't close the door to having a mechanism for the Board (or part of the Board) to be seated in a way other than self-selecting. But that begs the question of "by whom?" ... It just can't be "everyone." 

It would really need to be determined based on targeted constituencies, and I don't think should replace board-appointed board seats. Perhaps there would a seat elected by/for Speakers, and a seat elected by/for Organizers, and a seat elected by/for GitHub contributors.... But we need to identify those constituencies, and we would need some sort of track record to be able to form them. So even in an initial form, all seats would likely need to be appointed

**Comment by gavincampbell** [comment]
I'd be wary of incorporation unless the central org _needed_ to handle money - and if the central services can be provided without spending anything then this can be avoided for a long time - consulting that tax attorney might cost as much as the whole of Data Saturday Pordenone, and our recent experience suggests that HQ organisations are very good at generating costs for themselves which then need to be met somehow.

Agree there needs to be some mechanism for deciding who gets to decide which events get listed - these people will probably be the maintainers of the website. AFAIK the Python Steering council is unincorporated.

Final note on this is that DevOpsDays has a _for-profit_ partner called ConferenceOps, which does billing and accounts etc. for those events that aren't set up to do it themselves, but it's optional for events to use them and it certainly didn't exist on day 1. I think it might be US only.

**Comment by gavincampbell** [comment]
Oh, regarding voting. This used to be my field, I could bore for England on the subject. https://en.wikipedia.org/wiki/Schulze_method seems to be popular with the kids.

**Comment by SQLDBAWithABeard** [comment]
My tuppence

I would personally choose to avoid a US based organisation for two reasons

- The litigiousness 
- Alienation of the rest of the world

Until there is a need to handle money or assets, I am unsure as to the value proposition for an organisation.

There is an option which suggests that we could gain sponsorship for any required assets - Domain Names, infrastructure are the only two I see without requiring an organisation to hold any funds.

That said, I am not averse to some organisation within this open-source, community collaborative for decision making but right now, ensuring an organic growth and use of the resources is more important in my opinion.

The community resources that are already growing, from DCAC, from Microsoft, from community members are already replacing some of the facilities that were previously provided and it is worth holding out for a short period of time and letting the dust settle and see where this ends up.

**Comment by gavincampbell** [comment]
If the infrastructure is just GitHub pages, then this doesn't need any sponsorship. Email is a bit more problematic, but can be done for free up to a certain size. As far as I can see the only asset is the domain name.

**Comment by SQLDBAWithABeard** [comment]
Would Discussions be a better place for this conversation?

I have set up discussions on the repo and the link is here

https://github.com/sqlcollaborative/DataSaturdays/discussions

also available on the front page
