### ISSUE TITLE
Concerns

### ISSUE THREAD

**Issue by m82labs** [sqlcollaborative/DataSaturdays#60]
Hey folks, I just wanted to start a conversation because I fear this is starting another org that will just get big and need management. I am certainly being critical here but looking for constructive conversations. Not being negative to be negative. :)

Here are my concerns:

- Is this going to create a new clique of folks getting behind "datasaturday" events? 
- What is the plan to maintain this going forward? Providing folks with an "event in a box" solution where they can take some guides and recommendations and create an event is one thing, hosting all these event sites is another. Are there plans for what happens if this outgrows living on github pages? That's when money would start getting involved and a central org would need to be formed to handle that money
- Why are we not instead just backing existing projects, like https://datacommunity.events/?

Again, I'm not trying to be negative here, I'm just concerned. I want to avoid cliques as much as possible, and think we have a good opportunity to do that with PASS being gone (simply because it gives us a clean slate).

**Comment by spaghettidba** [comment]
> * Is this going to create a new clique of folks getting behind "datasaturday" events?

Just read all the issues that are happening here in the open. Do you seriously feel this is what is happening?

> * What is the plan to maintain this going forward? Providing folks with an "event in a box" solution where they can take some guides and recommendations and create an event is one thing, hosting all these event sites is another. Are there plans for what happens if this outgrows living on github pages? That's when money would start getting involved and a central org would need to be formed to handle that money

True. That's why I would really like this not to happen.

> * Why are we not instead just backing existing projects, like https://datacommunity.events/?

And who are the "clique of folks behind datacommunity.events", using your words? You see that there's no end to it? At the end of the day you have to trust somebody. Sorry if I'm being too harsh, but it's too easy to call it a clique: get involved, nodoby's barring you. 

Why DataSaturdays and not datacommunity.event? SQLSaturday is an establised brand that people recognize. That's the value we want to keep, but each local group organizes their own event. 
 
> Again, I'm not trying to be negative here, I'm just concerned. I want to avoid cliques as much as possible, and think we have a good opportunity to do that with PASS being gone (simply because it gives us a clean slate).

Excatly. Get involved, make your voice heard.

**Comment by SQLDBAWithABeard** [comment]
Please see the read me

This repository has been created as a place for the community create a set of tools and single point to enable people to run small regional events with little outlay or set-up diffculties to have open, transparent discussions on how it should be set up and utilised.

Your concerns about legal organisational issues are valid and there is a place for them in a separate issue. 

Datacommunity.events is an excellent project and should be supported.  However,  it is performing a different purpose as an aggregator for user groups. There are numerous other projects springing up as well.  That will always be difficult to handle but we can also work together for the benefit of the community.

Please help us to build this resource in an inclusive manner and if it provides a good service for events that people use, everyone benefits

**Comment by eugman** [comment]
So first let me say that even though I don't think your concerns are _likely_, I think they are perfectly normal and valid. I had similar worries about DataSaturdays being opaque or controlled by a few people that I didn't have much information about. Part of me was (irrationally) worried that you might have to be a dbatools contributor to significantly participate. Change and uncertainty is scary.

I can say that after reading through all the issues and discussions, I feel my initial worries were totally unfounded. I've seen quite a bit on discussion by people I know and trust, I have seen discussion by a wide variety of people from different backgrounds. I am currently quite optimistic about where this project is going.

@m82labs I would say we are all data people here, so I think the most helpful thing you could do on this issue is articulate how we could _measure_ these valid concerns coming true. What concrete things might we see that indicated that things were cliquish or overly centralized? And what issues could we raise to mitigate those possibilities?

**Comment by m82labs** [comment]
Thanks for the quick responses @eugman @SQLDBAWithABeard @spaghettidba!

I should explain my clique comments. I am one of the rare people that have NOT had great experiences with PASS in the past. I am actually trying to write a blog post about this topic and it has been difficult to say the least. To be less than specific though I have experienced a lot of cliques within the SQL community, especially at PASS events (including SQL Saturdays).  So my concerns are just coming from my past experiences. 

I see a lot of great people involved (including the folks that replied here) so I do have hope, I guess I am just cautious to get too excited. 

Measuring if my concerns are in fact happening is a tough one, and I think one for after the holidays. But I'll think on it. 

@SQLDBAWithABeard not sure if you were suggesting I create an issue to discuss the legal org concerns, or hinting that one exists already.

Thanks again for the responses and I *do* look forward to seeing what comes out of the this effort and what I might be able to contribute.

PS @spaghettidba no worries about sounding harsh, I hope I didn't sound harsh though admit my wording may have been less than diplomatic.

**Comment by SQLDBAWithABeard** [comment]
Would you be happy to close this issue and move this to the newly created discussions @m82labs ?

https://github.com/sqlcollaborative/DataSaturdays/discussions

also available on the front page

**Comment by m82labs** [comment]
Sounds good!
